# Generated by Django 2.0.13 on 2019-05-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('NO_DISPONIBLE', 'NO_DISPONIBLE'), ('DISPONIBLE', 'DISPONIBLE')], default='DISPONIBLE', max_length=80)),
                ('implemento', models.CharField(choices=[('NO_DISPONIBLE', 'NO_DISPONIBLE'), ('DISPONIBLE', 'DISPONIBLE')], default='DISPONIBLE', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField()),
                ('pago', models.PositiveIntegerField()),
            ],
        ),
    ]
