# Generated by Django 2.0.13 on 2019-05-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bicicleta',
            new_name='Implementodep',
        ),
    ]
