# Generated by Django 2.0.13 on 2019-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190508_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementodep',
            name='implemento',
            field=models.CharField(choices=[('NO_DISPONIBLE', 'NO_DISPONIBLE'), ('DISPONIBLE', 'DISPONIBLE')], default='PALETAS', max_length=80),
        ),
    ]
